name: Deploy website
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    environment: development
    env:
      DB_NAME: ${{ vars.DEV_DB_NAME }}
      DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
    needs: test
    runs-on: ubuntu-latest
    outputs:
      js-filename: ${{ steps.publish-js-filename.outputs.js-filename }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Output environment variables
        run: |
          echo "DB_NAME=$DB_NAME"
          echo "DB_PASSWORD=$DB_PASSWORD"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Publish JS filename
        id: publish-js-filename
        run: find dist/assets/*js -type f -execdir echo '::set-output name=js-filename::{}' ';'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
